### ISSUE TITLE
Change all text from json (lang.json), no plain text in components is allowed

### ISSUE THREAD

**Issue by yarindeoh** [yarindeoh/safe-home-haytiSham#35]
Maybe needs to add localization - I18n or other solution. 
Or keep using lang.json

**Comment by grount** [comment]
@yarindeoh Hey, I would like to help with this.
I would consider using [i18next](https://www.i18next.com/) and move from `lang.json` to js files starting from Hebrew as the default language. this change will be a breaking change for all the front-end not merged changes, if you would like to I can wait in order to avoid conflicts. WDYT?

**Comment by yarindeoh** [comment]
@grount  Sounds great! You can work on it. We are waiting for the server refactor change so we are mainly working on style changes
